### ISSUE TITLE
AccessViolationException when call Open

### ISSUE THREAD

**Issue by sdming** [openssl-net/openssl-net#3]
I  get `System.AccessViolationException` when call `OpenSSL.Crypto.CipherContext.Open(Byte[] input, Byte[] ekey, Byte[] iv, CryptoKey pkey)`

application stop at 
```
OpenSSL.Core.Native.EVP_OpenInit(IntPtr ctx, IntPtr type, Byte[] ek, Int32 ekl, Byte[] iv, IntPtr priv) 
```

os: win7 64bit

code:
```
using (CipherContext cc = new CipherContext(cipher))
{
    Envelope env = cc.Seal(new CryptoKey[] { key }, input);
    byte[] dd = cc.Open(output, env.Keys[0], env.IV, key);
}
```

**Comment by flaub** [comment]
Not sure what's going on here, but there is a unit test for this API here:

[TestCipher](../blob/master/test/TestCipher.cs#L79)
