### ISSUE TITLE
OpenSSL.Core.Native throws an exception.

### ISSUE THREAD

**Issue by nathikoza** [openssl-net/openssl-net#42]
I have installed the ManagedOpenSSL32(version: 0.6.1.0) Nuget Package to my ASP.NET MVC project, now the following peace of code throws an exception.

`
CryptoKey d = CryptoKey.FromPrivateKey(privateKey, null);
`
`using (var rsa = d.GetRSA())`
`{`
`byte[] byteResult = rsa.PrivateDecrypt(bin, RSA.Padding.PKCS1);`
`decodedString = Encoding.UTF8.GetString(byteResult);`
`}`

More specifically the first line. I downloaded the source code locally to test with a simple console app and the error happens on the BIO constructor with this parameter signature `(Byte[] buf)`, on this line of code `OpenSSL.Core.Native.BIO_s_mem()`. 

This the exception message 

> Unable to load DLL 'x86\libeay32': The specified module could not be found.

**Comment by flaub** [comment]
It's unclear where this NuGet package comes from, it's not associated with this project at all.

In any case, it seems like you're missing the native library.

Take a look at:
https://github.com/openssl-net/openssl-net/blob/master/INSTALL

**Comment by nathikoza** [comment]
@flaub thanks for the quick response.

I didn't know that the wrapper was not associated with this project, in any case you can check it out here [https://www.nuget.org/packages/ManagedOpenSsl32/](here)

**Comment by nathikoza** [comment]
@flaub thanks, got it to work by modifying the csproj file to copy the dlls to the bin every time I build and deploy.
