### ISSUE TITLE
DllNotFoundException libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by almunt** [openssl-net/openssl-net#6]
OSX 10.7.3
MONO 3.0.12

Unhandled Exception:
System.TypeInitializationException: An exception was thrown by the type initializer for PtpCore.Encryption.SecurityContext ---> System.TypeInitializationException: An exception was thrown by the type initializer for OpenSSL.Crypto.Cipher ---> System.TypeInitializationException: An exception was thrown by the type initializer for OpenSSL.Core.Native ---> System.DllNotFoundException: /Library/Frameworks/Mono.framework/Versions/3.0.12/lib/libssl.1.0.0.dylib
  at (wrapper managed-to-native) OpenSSL.Core.Native:SSL_load_error_strings ()
  at OpenSSL.Core.Native..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at OpenSSL.Crypto.Cipher..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  --- End of inner exception stack trace ---

**Comment by flaub** [comment]
I think perhaps the `dllmap` entry for osx is wrong. I'll try to repro this on an appropriate machine once I'm near it.

**Comment by flaub** [comment]
This happens when the runtime can't find the native dylib. When running unit tests on OSX, I've had to do this, for example:

```
DYLD_LIBRARY_PATH=/usr/local/Cellar/openssl/1.0.2a-1/lib/ mono /Library/Frameworks/Mono.framework/Versions/4.0.1/lib/mono/4.5/nunit-console.exe bin/Debug/UnitTests.dll
```

YMMV.

You can also use:

```
MONO_LOG_LEVEL=debug mono --debug $YOUR_EXE
```

This will spew a lot, but it should tell you how the system is looking for dylibs.

**Comment by m-ivanov** [comment]
this issue is still open! visual studio ce 7.4.3 , mono 5.8.1.0
